#!/usr/bin/env python

"""
Copyright kubeinit contributors.

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at:

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
"""

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6aa97e1b29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """
    Upgrade command form alembic.

    This is the upgrade method
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=120),
                              nullable=True),
                    sa.Column('email', sa.String(length=120),
                              nullable=True),
                    sa.Column('password', sa.String(length=30),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username'))
    # ### end Alembic commands ###


def downgrade():
    """
    Downgrade command form alembic.

    This is the downgrade method
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
